/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check
const fs = require('fs');
const path = require('path');
const {countMarkdownFilesRecursive, stripNumericPrefix} = require('./navigation-utils');

// Set to true to use root-level folders as navbar items, false for default Docusaurus sidebar
// Can be overridden by setting NAVBAR_AS_ROOT environment variable to 'true'
const navbarAsRoot = process.env.NAVBAR_AS_ROOT === 'true'; // Default: false unless explicitly set to 'true'

// Dynamically generate sidebars from docs folder structure
function generateSidebars() {
  // If not using navbar as root, return default sidebar structure
  if (!navbarAsRoot) {
    return {
      tutorialSidebar: [
        {
          type: 'autogenerated',
          dirName: '.',
        },
      ],
    };
  }
  
  // Otherwise, generate individual sidebars for each top-level folder
  const docsPath = path.join(__dirname, 'docs');
  /** @type {Record<string, any[]>} */
  const sidebars = {};
  
  try {
    const entries = fs.readdirSync(docsPath, { withFileTypes: true });
    
    for (const entry of entries) {
      if (entry.isDirectory() && !entry.name.startsWith('.')) {
        // Count markdown files recursively to include nested subdirectories
        const dirPath = path.join(docsPath, entry.name);
        const markdownCount = countMarkdownFilesRecursive(dirPath);
        
        // Create a sidebar for any top-level folder that contains docs
        if (markdownCount > 0) {
          const sidebarId = stripNumericPrefix(entry.name);
          
          console.log(`Generating sidebar: ${entry.name} -> ${sidebarId} (${markdownCount} files)`);
          
          sidebars[sidebarId] = [
            {
              type: 'autogenerated',
              dirName: entry.name,
            },
          ];
        } else {
          console.log(`Skipping sidebar for ${entry.name} (no docs found)`);
        }
      }
    }
    
    console.log('Generated sidebars:', Object.keys(sidebars));
  } catch (error) {
    console.warn('Could not read docs directory:', error);
  }
  
  return sidebars;
}

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = generateSidebars();

module.exports = sidebars;