/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check
const fs = require('fs');
const path = require('path');

// Set to true to use root-level folders as navbar items, false for default Docusaurus sidebar
// Can be overridden by setting NAVBAR_AS_ROOT environment variable to 'true'
const navbarAsRoot = process.env.NAVBAR_AS_ROOT === 'true'; // Default: false unless explicitly set to 'true'

// Convert folder/file names to human-readable labels
function humanize(str) {
  return str
    // Remove file extensions
    .replace(/\.[^/.]+$/, '')
    // Split on capital letters, underscores, and hyphens
    .replace(/([a-z])([A-Z])/g, '$1 $2')
    .replace(/[_-]/g, ' ')
    // Capitalize first letter of each word
    .split(' ')
    .map(word => word.charAt(0).toUpperCase() + word.slice(1))
    .join(' ');
}

// Dynamically generate sidebars from docs folder structure
function generateSidebars() {
  // If not using navbar as root, return default sidebar structure
  if (!navbarAsRoot) {
    return {
      tutorialSidebar: [
        {
          type: 'autogenerated',
          dirName: '.',
        },
      ],
    };
  }
  
  // Otherwise, generate individual sidebars for each top-level folder
  const docsPath = path.join(__dirname, 'docs');
  const sidebars = {};
  
  try {
    const entries = fs.readdirSync(docsPath, { withFileTypes: true });
    
    for (const entry of entries) {
      if (entry.isDirectory() && !entry.name.startsWith('.')) {
        // Count markdown files in the directory
        const dirPath = path.join(docsPath, entry.name);
        const files = fs.readdirSync(dirPath, { withFileTypes: true });
        const mdFiles = files.filter(f => 
          f.isFile() && (f.name.endsWith('.md') || f.name.endsWith('.mdx'))
        );
        
        // Only create a sidebar if there's more than one file
        if (mdFiles.length > 1) {
          const sidebarId = entry.name.replace(/^\d+_/, '');
          
          console.log(`Generating sidebar: ${entry.name} -> ${sidebarId} (${mdFiles.length} files)`);
          
          sidebars[sidebarId] = [
            {
              type: 'autogenerated',
              dirName: entry.name,
            },
          ];
        } else {
          console.log(`Skipping sidebar for ${entry.name} (only ${mdFiles.length} file)`);
        }
      }
    }
    
    console.log('Generated sidebars:', Object.keys(sidebars));
  } catch (error) {
    console.warn('Could not read docs directory:', error);
  }
  
  return sidebars;
}

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = generateSidebars();

module.exports = sidebars;