# Static information for this action template
# Source: https://github.com/GitTools/actions
name: ".NET Test"
description: "Build and test a dotnet project"

# Inputs (parameters) for this action
inputs:
  dotnet-version:
    description: The dotnet version of the project to build and test.
    required: false
    default: 6.0.x
  docker_registry_username:
    description: "Username for docker image registry"
    required: false
  docker_registry_password:
    description: "Password for docker image registry"
    required: false
  docker_file:
    description: "name of the dockerfile to use. Default: Dockerfile"
    required: false
    default: "Dockerfile"
  
# Steps to run
runs:
  using: "composite"
  
  steps:
    ### Checkout repo
    - uses: actions/checkout@v3

    ### Build and test all projects
    - name: .NET Test
      uses: gvdmeijde/githubactions/dotnet-build-test@main
      with:
        test-output: "test-results.trx"

    ### Publish nugets
    - name: Get nuget projects
      id: get_nuget_files
      uses: gvdmeijde/githubactions/get-file-names@main
      with:
        filter: "*.NuGet.csproj"

    - name: Print files
      shell: bash
      run: |
          for f in ${{ steps.get_nuget_files.outputs.files }}; do
            echo $f detected
          done

    ### Build and publish SimpleWebServer image to dockerhub
    - name: docker build
      if: success() && "${{ github.event.inputs.docker_registry_username != '' }}" && "${{ github.event.inputs.docker_registry_password != '' }}"
      uses: gvdmeijde/githubactions/publish-docker@main
      with:
        registry_username: "${{ inputs.docker_registry_username }}"
        registry_password: "${{ inputs.docker_registry_password }}"
        image_name: "simplefileserver"
        tag: "latest"
        docker_file: "${{ inputs.docker_file }}"
