# Static information for this action template
# Source: https://github.com/GitTools/actions
name: ".NET Test"
description: "Build and test a dotnet project"

# Inputs (parameters) for this action
inputs:
  docker_image_name:
    description: The name of the docker image to create and push.
    required: false
    default: ''
  docker_registry_username:
    description: "Username for docker image registry"
    required: false
  docker_registry_password:
    description: "Password for docker image registry"
    required: false
  docker_file:
    description: "name of the dockerfile to use. Default: Dockerfile"
    required: false
    default: "Dockerfile"
  nuget_api_source:
    description: "NuGet server uri hosting the packages"
    required: false
    default: "https://www.nuget.org"
  nuget_api_key:
    description: "API key to authenticate with NuGet server"
    required: false
    default: ''
  
# Steps to run
runs:
  using: "composite"
  
  steps:
    ### Checkout repo
    - uses: actions/checkout@v3

    ### Build and test all projects
    - name: Run unittests
      uses: kingtechnl/githubactions/dotnet-build-test@main
      with:
        test_output: "test-results.trx"

    ### Get version number
    - name: Get version
      id: get_version
      uses: kingtechnl/githubactions/gitversion@main


    ### Test conditions
    - name: If condition is not set
      if: ${{ inputs.docker_registry_username != '' }}
      shell: bash
      run: |
        echo "docker_registery_username = ${{inputs.docker_registry_username}}"
    - name: Else, if condition is set
      if: ${{ inputs.docker_registry_username == '' }}
      shell: bash
      run: |
        echo "no docker_registery_username set"

    ### Publish nugets    
    - name: Build and publish NuGet projects
      if: ${{ inputs.nuget_api_key != '' }}
      uses: kingtechnl/githubactions/publish-nuget@main
      with:
        nuget_version: ${{ steps.get_version.outputs.version }}
        nuget_api_source: ${{ inputs.nuget_api_source }}
        nuget_api_key: ${{ inputs.nuget_api_key }}

    ### Build and publish docker image to dockerhub
    - name: Build and publish docker image
      if: ${{ success() && inputs.docker_registry_username != '' && inputs.docker_registry_password != '' }}
      uses: kingtechnl/githubactions/publish-docker@main
      with:
        registry_username: "${{ inputs.docker_registry_username }}"
        registry_password: "${{ inputs.docker_registry_password }}"
        image_name: "${{ inputs.docker_image_name }}"
        tags: "${{ steps.get_version.outputs.version }};${{ steps.get_version.outputs.branchTag }}"
        docker_file: "${{ inputs.docker_file }}"
