name: Docusaurus build

# Triggers
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

#: Jobs to execute
jobs:
  ## Build all projects
  build:
    runs-on: self-hosted
    steps:
    ### Checkout repo
    - uses: actions/checkout@v3

    ### Generate static website using docusaurus
    - name: Build docusaurus site
      id: build_docusaurus
      uses: kingtechnl/githubactions/docusaurus@main
      with:
        sourceDir: 'docs' #Directory the source files are stored in.
        targetDir: 'build' #Directory the generated website will be stored in.
        siteName: 'my-website' #Optional name for website, default: my-website
        version: 'latest' #Optional docusaurus version, default: latest
        variant: 'javascript' #Optional docusaurus variant, default: javascript
        template: 'classic' #Optional docusaurus template, default: classic
