# Static information for this action template
# Source: https://github.com/GitTools/actions
name: ".NET Test"
description: "Build and test a dotnet project"

# Inputs (parameters) for this action
inputs:
  nuget_projects:
    description: Names of all projects to publish as NuGet, delimited by ;
    required: false
    default: ''
  nuget_version:
    description: Version number for NuGet package
    required: true
    default: ''
  nuget_api_source:
    description: NuGet server uri hosting the packages
    required: false
    default: "https://www.nuget.org"
  nuget_api_key:
    description: API key to authenticate with NuGet server
    required: true
    default: ''
    
# Steps to run
runs:
  using: "composite"  
  steps:

    # If no NuGet project is given, we look for projects ending with '.NuGet.csproj'
    - name: Get NuGet projects
      if: ${{ inputs.nuget_projects == ''}}
      id: get_nuget_projects
      uses: Rishabh510/Path-lister-action@master
      with:
        path: "/"
        type: ".NuGet.csproj"

    - name: Print detected NuGet projects
      if: ${{ inputs.nuget_projects == ''}}
      shell: bash
      run: |
        echo "Found ${{ steps.get_nuget_projects.outputs.path_count }} nuget project(s):"
        for i in ${{ steps.get_nuget_projects.outputs.paths }}; do
          echo ${i##"/github/workspace/"}
        done

    - name: Print nuget API
      if: ${{ success() }}
      shell: bash
      run: |
        echo "Pushing nugets V${{ inputs.nuget_version }} to ${{ inputs.nuget_api_source }}"

    - name: Setup .NET
      uses: actions/setup-dotnet@v3 #v2
      with:
        dotnet-version: | 
          3.1.x
          5.0.x
          6.0.x
    
    - name: Build solution
      if: ${{ success() && inputs.nuget_projects != ''}}
      shell: bash
      run: dotnet build -p:Version=${{ inputs.nuget_version }}

    # pack all projects ending with '.NuGet.csproj'
    - name: Create NuGets
      if: ${{ success() && inputs.nuget_projects == ''}}
      shell: bash
      run: |
        for project in ${{ steps.get_nuget_projects.outputs.paths }}; do
          echo packing ${project##"/github/workspace/"} with version: ${{ inputs.nuget_version }}
          dotnet pack ${project##"/github/workspace/"} --no-build -p:Version=${{ inputs.nuget_version }}
        done

    # pack all projects passed in input.
    - name: Create NuGets
      if: ${{ success() && inputs.nuget_projects != ''}}
      shell: bash
      run: |
        IFS=';' read -r -a project_array <<< "${{ inputs.nuget_projects }}"
        for project in project_array; do
          dotnet pack $project --no-build -p:Version=${{ inputs.nuget_version }}
        done

    # publish all packages
    - name: Publish NuGets
      if: success()
      shell: bash
      run: |
        echo "Pushing nugets to ${{ inputs.nuget_api_source }}..."
        dotnet nuget push **\*.nupkg --source "${{ inputs.nuget_api_source }}" --api-key "${{ inputs.nuget_api_key }}" --skip-duplicate
