# Static information for this action template
name: "Publish docker"
description: "Build a container image and Pushes it to Docker registry"

# Inputs (parameters) for this action
inputs:
  registry_username:
    description: "Username for image registry"
    required: true
  registry_password:
    description: "Password for image registry"
    required: true
  image_name:
    description: "Name of the image to push"
    required: true
  tag: 
    description: "How to tag the image. Default: latest" 
    required: false
    default: "latest"
  docker_file:
    description: "name of the dockerfile to use. Default: Dockerfile"
    required: false
    default: "Dockerfile"

runs:
  using: "composite"
  steps:
    - name: docker build
      if: success()
      run: docker build . -f ${{inputs.docker_file}} --tag ${{ secrets.DOCKERHUB_USERNAME }}/${{inputs.image_name}}:${{inputs.tag}}

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ inputs.registry_username }}
        password: ${{ inputs.registry_password }}

    - name: docker push
      if: success()
      run: docker push ${{ inputs.registry_username }}/${{inputs.image_name}}